
default: &default
  adapter: postgresql
  encoding: unicode  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: postgres
  database: my_awesome_api_development

test:
  <<: *default
  username: postgres
  database: my_awesome_api_test

production:
  <<: *default
  database: my_awesome_api_production
  username: my_awesome_api
  password: <%= ENV['MY_AWESOME_API_DATABASE_PASSWORD'] %>
